### ISSUE TITLE
pomdp-solver takes options in the format -<option> <value> and not --<option> <value>

### ISSUE THREAD

**Issue by mhoehle** [JuliaPOMDP/POMDPSolve.jl#5]
I tried to change the horizon and stdout argument when creating an POMDPSolve, but was puzzled that these arguments were ignored. For example:

solver = POMDPSolveSolver(stdout="foo.bar", horizon=1)

The code in
https://github.com/JuliaPOMDP/POMDPSolve.jl/blob/79f4cdda8a95613ff3af62444301dfd19a29341a/src/utils.jl#L6

generates the call:
/Users/hoehle/.julia/v0.6/POMDPSolve/deps/pomdp-solve-master/src/pomdp-solve -pomdp /Users/hoehle/.julia/v0.6/POMDPSolve/test/tiger.pomdp -o mypolicy --horizon 1 --stdout foo.bar

From this it becomes clear that the double slash in line 6 is too much, because it should be -horizon 1 -stdout foo.bar as arguments to the pomdp-solve program. 

I could also submit this as a PR, but it doesn't seem worthwhile for changing the single character in the file. Let me know, if you think otherwise.

**Comment by zsunberg** [comment]
Hi @hoehleatsu. Thanks for pointing this out! It's usually worth it to make a simple PR because that causes Travis-CI to run automatically so that we can catch errors. You can submit a PR via the github online interface with a few clicks by using the pencil icon at the top right of any file. Then you don't have to make any branches or do anything with git on your computer. I just went ahead and did it this time (#6). Will merge as soon as the tests run successfully.

**Comment by mhoehle** [comment]
Thanks!
